name: 17 - 3 - Custom Actions - Docker

on:
  workflow_dispatch:
    inputs:
      url:
        type: choice
        options:
          - 'https://www.google.com'
          - 'https://www.invalid-aidfghaidgfiazgd.com'
          - 'invalid-aidfghaidgfiazgd'

jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ping URL
        id: ping-url
        uses: ./.github/actions/docker-ping-url
        with:
          url: ${{ inputs.url }}